# Generated by Django 4.2.7 on 2023-11-24 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MarketStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Bike', 'Bike'), ('Car', 'Car'), ('Character', 'Character'), ('Parts', 'Parts')], max_length=50)),
                ('status', models.CharField(choices=[('Sale', 'Sale'), ('Pending', 'Pending'), ('Sale out', 'Sale out')], default='Sale', max_length=50)),
                ('data', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_listed', to='store.user')),
            ],
        ),
    ]
