# Generated by Django 4.2.7 on 2023-11-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_marketplaceitem_remove_user_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketplaceitem',
            old_name='listing_price',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='marketplaceitem',
            name='data',
            field=models.TextField(),
        ),
    ]
