# Generated by Django 4.2.7 on 2023-11-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_listing_price_marketplaceitem_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='LoginUser',
        ),
    ]
