# Generated by Django 4.2.7 on 2023-11-28 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='listing',
        ),
    ]
