# Generated by Django 4.2.7 on 2023-11-28 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_transaction_seller_transaction_listing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('car', 'Car'), ('bus', 'Bus'), ('bike', 'Bike'), ('character', 'Character'), ('parts', 'Parts')], max_length=20),
        ),
    ]
